services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn DjangoProject.wsgi:application --bind 0.0.0.0:8000 --certfile=/path/to/cert.pem --keyfile=/path/to/key.pem

    ports:
      - "8000:8000"  # Mapea el puerto 8000 del contenedor al puerto 80 del host
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS = ['portfolio-production-5731.up.railway.app', 'localhost', '127.0.0.1']
