services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=portfolio-production-5731.up.railway.app,localhost,127.0.0.1
    expose:
      - "8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf


    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
