services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app


    environment:
      - DEBUG=False
      - ALLOWED_HOSTS="127.0.0.1,localhost,portfolio-production-5731.up.railway.app,pablotech.com"
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./static:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - web
