services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn DjangoProject.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"  # Mapea el puerto 8000 del contenedor al host
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      - db
    environment:
      DEBUG: "False"
      ALLOWED_HOSTS: "127.0.0.1,localhost,116.203.18.47,pablotech.dev,www.pablotech.dev"
      DATABASE_URL: "postgres://django_user:password123@db:5432/django_db"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: django_db
    ports:
      - "5432:5432"  # Esto ahora está correctamente alineado

volumes:
  media:
  static:
