services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/app/static
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=pablotech.com,localhost,127.0.0.1
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./static:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
