<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-12-04 15:38
=======
# Generated by Django 5.1.3 on 2024-12-10 16:42
>>>>>>> end_version

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("portfolio", "0001_initial"),
=======
        ('portfolio', '0001_initial'),
>>>>>>> end_version
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="personalinfo",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/profile.jpeg"
            ),
=======
            model_name='personalinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/profile.jpg'),
>>>>>>> end_version
        ),
    ]
