# Generated by Django 5.1.3 on 2024-12-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_personalinfo_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
    ]
